# -*- coding: utf-8 -*-
"""ModeloPreverCNH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kviD5ZRA0Kib102QsW2yZzRbUgKA4OoH
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models,optimizers
from google.colab import drive
import matplotlib.pyplot as plt
import os
import numpy as np

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print('GPU não encontrada! Verifique as configurações.')
else:
  print(f'Sucesso! GPU encontrada em: {device_name}')

drive.mount('/content/drive')

!unzip -qo "/content/drive/My Drive/projeto_cnh/dataset.zip" -d "/content/dataset_local"
pasta_dir = '/content/dataset_local/dataset'


train_ds = tf.keras.utils.image_dataset_from_directory(
    pasta_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(254, 254),
    batch_size=32
)
val_ds = tf.keras.utils.image_dataset_from_directory(
    pasta_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(254, 254),
    batch_size=32
)

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(254, 254, 3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False


modelo = models.Sequential([

    layers.Rescaling(1./255, input_shape=(254, 254, 3)),
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.3),
    layers.RandomZoom(0.3),
    layers.RandomContrast(0.2),

    base_model,


    layers.GlobalAveragePooling2D(),
    layers.Dropout(0.5),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])


modelo.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)


treino = modelo.fit(train_ds, epochs=15, validation_data=val_ds)


modelo.save('/content/drive/My Drive/projeto_cnh/modelo_cnh_final.keras')
print("Modelo treinado!")

